#ifndef KITCHENSOUND_PAGES_H
#define KITCHENSOUND_PAGES_H

enum PAGES {
    INACTIVE,
    LOADING,
    STREAM_SELECTION,
    STREAM_PLAYING,
    BT_PLAYING,
    OPTIONS,
    MENU_SELECTION,
    SNAPCAST_PLAYING
};

#endif //KITCHENSOUND_PAGES_H
